ALTER TABLE merchants
ADD COLUMN IF NOT EXISTS card_tagline TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS card_theme TEXT NOT NULL DEFAULT 'gold',
ADD COLUMN IF NOT EXISTS card_style TEXT NOT NULL DEFAULT 'modern',
ADD COLUMN IF NOT EXISTS card_bg_color TEXT NOT NULL DEFAULT '#1a1208',
ADD COLUMN IF NOT EXISTS card_bg2_color TEXT NOT NULL DEFAULT '#241a09',
ADD COLUMN IF NOT EXISTS card_accent_color TEXT NOT NULL DEFAULT '#c9a84c',
ADD COLUMN IF NOT EXISTS card_accent2_color TEXT NOT NULL DEFAULT '#e8c96a',
ADD COLUMN IF NOT EXISTS card_text_color TEXT NOT NULL DEFAULT '#fdf6e3',
ADD COLUMN IF NOT EXISTS card_text_muted_color TEXT NOT NULL DEFAULT 'rgba(253,246,227,0.55)',
ADD COLUMN IF NOT EXISTS card_stamp_color TEXT NOT NULL DEFAULT 'rgba(201,168,76,0.15)',
ADD COLUMN IF NOT EXISTS card_logo_url TEXT NOT NULL DEFAULT '';
